### ISSUE TITLE
Failure to install libtdsodbc.so file

### ISSUE THREAD

**Issue by David-Degnan** [PNNL-Comp-Mass-Spec/PNNL.DMS.utils#15]
Hello there, 

Mac user here. I have one of the "Apple M1 Max" chips. I followed the brew install instructions but could not get the libtdsodbc.so file to show up in my /usr/local/lib folder. I did confirm with brew list that freetds and unixodbc were installed. Any tips/tricks to solve this issue? 

Thanks!

**Comment by Ben-Drucker** [comment]
Hi, on computers that use the M Series chips, homebrew gets installed in a different directory (`/opt/homebrew/`). Therefore, you can find (an alias for) `libtdsodbc.so` in `/opt/homebrew/lib`. [If you're in Finder and secondary click on this alias, and then click _show original_, you will be brought to the original file.] I will update the documentation to this effect. Thanks for pointing this out!
