### ISSUE TITLE
read_msfragger_data_from_DMS fails when column "Quan Usage" is absent

### ISSUE THREAD

**Issue by skelly001** [PNNL-Comp-Mass-Spec/PNNL.DMS.utils#23]
The "Quan Usage" column was used as a reference column to omit sample-specific peptide intensity data when reading. 
Problem: "Quan Usage" column is not always present. 
Possible cause: "Quan Usage" column may only be created when TMT Integrator is run.

https://github.com/PNNL-Comp-Mass-Spec/PNNL.DMS.utils/blob/e00ce8fa1671b9bad752bde8a8ff314e19781374/R/read_msfragger_data_from_DMS.R#L73C39-L73C39

**Comment by TylerSagendorf** [comment]
Can "Mapped Proteins" be used as the final column instead, or can we select just those columns that are used within the function itself?

![image](https://github.com/PNNL-Comp-Mass-Spec/PNNL.DMS.utils/assets/57922480/2cdc1082-93c4-4a70-a72c-618a678c3c15)
