### ISSUE TITLE
Add "get_raw_files_by_dataset_package" function to copy raw files from DMS

### ISSUE THREAD

**Issue by skelly001** [PNNL-Comp-Mass-Spec/PNNL.DMS.utils#30]
Add "get_raw_files_by_dataset_package" function to copy raw files from DMS. Code blow can be adapted to make the function.

library(PNNL.DMS.utils)

jobRecords <- get_job_records_by_dataset_package(5077)
jobRecords <- subset(jobRecords, Tool == "MASIC_Finnigan") # one to one mapping with datasets
for( j in jobRecords$Job ){
   fpath = get_tool_output_files_for_job_number( j, NULL, "raw")
   file.copy( fpath, ".")
}

**Comment by TylerSagendorf** [comment]
@skelly001 Rename this to `get_raw_files_from_DMS`. We do not use "_by_dataset_package" in function names anymore. Make sure to update documentation as well and run `devtools::document()`.

**Comment by skelly001** [comment]
Got it. Thanks Tyler

**Comment by vladpetyuk** [comment]
addressed in this commit: https://github.com/PNNL-Comp-Mass-Spec/PNNL.DMS.utils/commit/51ded262104a65ae3b1d56d1380f0abd0458aa87
and this: https://github.com/PNNL-Comp-Mass-Spec/PNNL.DMS.utils/commit/d3c5aa2a8fa8e6d13c08b12ff9dde1e4e2009932
