### ISSUE TITLE
Parsing failures when reading MASIC data

### ISSUE THREAD

**Issue by mdnestor** [PNNL-Comp-Mass-Spec/PNNL.DMS.utils#5]
Reading MASIC data can throw errors if the first 1000 columns contain only zeroes. Reproducible example below:

```
jr <- get_job_records_by_dataset_package(3676)
x <- get_results_for_multiple_jobs.dt(jr[1,])
```
Output:
```
Warning: 314794 parsing failures.
 row                       col           expected actual                                                                                                                                                                                 file
1315 Ion_130.135_SignalToNoise 1/0/T/F/TRUE/FALSE  2.06  (dataset_name)
1315 Ion_130.135_Resolution    1/0/T/F/TRUE/FALSE  46400 (dataset_name)
1339 Ion_127.125_SignalToNoise 1/0/T/F/TRUE/FALSE  9.97  (dataset_name)
1339 Ion_128.128_SignalToNoise 1/0/T/F/TR [... truncated]
```

One solution is to suppress warnings on the `read_tsv` call. But this could hide other important warnings. Ideally we can suppress expected boolean errors specifically.

**Comment by TylerSagendorf** [comment]
I ran this example with the most recent updates, and it didn't throw an error. It might have been a missing dependency or argument mismatch (variable in function definition has a different name in the function body) that caused the problem.

**Comment by skelly001** [comment]
Looks like this has been fixed. Tested the code and did not get any errors
